# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: plex
spec:
  secretName: plex-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: plex.ajphome.com
  dnsNames:
  - plex.ajphome.com
