# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-tls
  namespace: jellyfin
spec:
  secretName: filebrowser-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: filebrowser.ajphome.com
  dnsNames:
  - filebrowser.ajphome.com
