# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: media.ajphome.com
spec:
  type: LoadBalancer
  selector:
    app: nfs-server
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP
  - name: nfs-udp
    port: 2049
    targetPort: 2049
    protocol: UDP
  - name: rpcbind
    port: 111
    targetPort: 111
    protocol: TCP
  - name: rpcbind-udp
    port: 111
    targetPort: 111
    protocol: UDP
