# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 5m0s
  path: ./cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  targetNamespace: cert-manager
