# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  targetNamespace: jellyfin
  install:
    createNamespace: false
  chart:
    spec:
      chart: filebrowser
      version: 1.0.*
      sourceRef:
        kind: HelmRepository
        name: filebrowser
        namespace: flux-system
  interval: 10m0s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: jellyfin-filebrowser
            spec:
              template:
                spec:
                  volumes:
                    - name: config
                      configMap:
                        defaultMode: 420
                        name: jellyfin-filebrowser
                    - name: media
                      persistentVolumeClaim:
                        claimName: jellyfin-jellyfin-media
                  containers:
                    - name: filebrowser
                      volumeMounts:
                        - mountPath: /.filebrowser.json
                          name: config
                          subPath: .filebrowser.json
                        - mountPath: /srv
                          name: media
  values:
    image:
      repository: filebrowser/filebrowser
      tag: v2.31.2
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    persistence:
      enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    ingress:
      enabled: true
      hosts:
        - host: filebrowser.ajphome.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - filebrowser.ajphome.com
          secretName: filebrowser-tls

    env:
      - name: FB_ROOT
        value: "/srv"
      - name: FB_NOAUTH
        value: "false"
