# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
spec:
  targetNamespace: intel-gpu-plugin
  install:
    createNamespace: true
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.*
      sourceRef:
        kind: HelmRepository
        name: intel
  interval: 10m0s
  dependsOn:
    - name: device-plugin-operator
    - name: nfd
  values:
    enableMonitoring: true
    logLevel: 2
