# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  dependsOn:
    - name: gpu-device-plugin
  targetNamespace: jellyfin
  install:
    createNamespace: true
  chart:
    spec:
      chart: jellyfin
      version: 2.7.*
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  interval: 10m0s
  values:
    podPrivileges:
      hostNetwork: true

    # Deployment strategy must be Recreate due to hostNetwork port binding
    # requirements for DLNA (ports 1900, 7359). Rolling updates would fail
    # as new pods cannot bind to ports still held by terminating pods.
    deploymentStrategy:
      type: Recreate

    jellyfin:
      enableDLNA: true

    env:
      TZ: America/New_York
      JELLYFIN_CACHE_DIR: /cache

    service:
      type: ClusterIP
      port: 8096

    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: topolvm-provisioner
        accessMode: ReadWriteOnce
        size: 10Gi
      media:
        enabled: true
        type: pvc
        storageClass: topolvm-provisioner
        accessMode: ReadWriteOnce
        size: 1Ti
      cache:
        enabled: true
        type: pvc
        storageClass: topolvm-provisioner
        accessMode: ReadWriteOnce
        size: 50Gi

    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
        gpu.intel.com/i915: "1"
      limits:
        memory: 4Gi
        gpu.intel.com/i915: "1"

    ingress:
      enabled: true
      hosts:
        - host: jellyfin.ajphome.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyfin.ajphome.com
          secretName: jellyfin-tls

    securityContext:
      capabilities:
        drop:
          - "ALL"
      privileged: false
