# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 5m0s
  path: ./metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-pki
  targetNamespace: metallb-system
