# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-server
spec:
  targetNamespace: jellyfin
  install:
    createNamespace: false
  chart:
    spec:
      chart: nfs-server-provisioner
      version: 1.8.*
      sourceRef:
        kind: HelmRepository
        name: nfs-ganesha
        namespace: flux-system
  interval: 10m0s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: nfs-server-nfs-server-provisioner
            spec:
              template:
                spec:
                  volumes:
                    - name: data
                      persistentVolumeClaim:
                        claimName: jellyfin-jellyfin-media
  values:
    # Disable default persistence - we'll inject the existing PVC via postRenderer
    persistence:
      enabled: false

    # Expose NFS via LoadBalancer (MetalLB)
    service:
      type: LoadBalancer
      nfsPort: 2049
      mountdPort: 20048
      rpcbindPort: 111

    # Do NOT create a StorageClass (we're using this as a simple NFS export)
    storageClass:
      create: false

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
