# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
spec:
  targetNamespace: plex
  install:
    createNamespace: true
  chart:
    spec:
      chart: plex-media-server
      version: 1.4.*
      sourceRef:
        kind: HelmRepository
        name: plex
  interval: 10m0s
  values:
    # Config PVC - reference existing data
    pms:
      configExistingClaim: plex-plex-config
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          memory: 4Gi

    # Environment variables
    extraEnv:
      TZ: America/New_York

    # Service configuration
    service:
      type: ClusterIP
      port: 32400

    # Additional volumes for media
    extraVolumes:
      - name: media
        persistentVolumeClaim:
          claimName: plex-plex-media

    extraVolumeMounts:
      - name: media
        mountPath: /media

    # Ingress configuration
    ingress:
      enabled: true
      url: plex.ajphome.com
      tls:
        - hosts:
            - plex.ajphome.com
          secretName: plex-tls
