# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  targetNamespace: traefik-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: 37.1.*
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 10m0s
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
